/**
 * generated by Xtext
 */
package org.xtext.editor.yang.ui.contentassist;

import org.xtext.editor.yang.ui.contentassist.AbstractYangProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class YangProposalProvider extends AbstractYangProposalProvider {
}
