/*
 * generated by Xtext
 */
package org.xtext.editor.yang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class YangRuntimeModule extends org.xtext.editor.yang.AbstractYangRuntimeModule {

}
