/*
* generated by Xtext
*/
package org.xtext.editor.yang.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.editor.yang.services.YangGrammarAccess;

public class YangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private YangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.editor.yang.parser.antlr.internal.InternalYangParser createParser(XtextTokenStream stream) {
		return new org.xtext.editor.yang.parser.antlr.internal.InternalYangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "YangFile";
	}
	
	public YangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(YangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
