/**
 * generated by Xtext
 */
package org.xtext.editor.yang.validation;

import org.xtext.editor.yang.validation.AbstractYangValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class YangValidator extends AbstractYangValidator {
}
